version: '3.7'

services:
  postgres:
    image: postgres:16.4
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - pgdata:/data/postgres

  urls:
    build:
      context: ./
      dockerfile: ./apps/urls/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

    depends_on:
      - postgres
    command: yarn nodemon -L --ext ts,json --watch apps --watch libs --exec "yarn start urls"

volumes:
  pgdata:
    driver: local
