version: '3.7'

services:
  teddy-postgres:
    container_name: teddy-postgres
    image: postgres:16.4
    restart: unless-stopped
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - pgdata:/data/postgres
    env_file:
      - ./.env.example

  teddy-urls:
    container_name: teddy-urls
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./apps/urls/Dockerfile
    ports:
      - '3000:3000'

    volumes:
      - ./apps:/usr/src/apps
      - ./libs:/usr/src/libs

    depends_on:
      - teddy-postgres
    command: npm run start:dev urls
    env_file:
      - ./.env.example

  teddy-users:
    container_name: teddy-users
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./apps/users/Dockerfile
    ports:
      - '3001:3000'

    volumes:
      - ./apps:/usr/src/apps
      - ./libs:/usr/src/libs

    depends_on:
      - teddy-postgres
    command: npm run start:dev users
    env_file:
      - ./.env.example

volumes:
  pgdata:
    driver: local
