version: '3.7'

services:
  postgres:
    image: postgres:16.4
    ports:
      - '8080:${DB_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - pgdata:/data/postgres

  urls:
    build:
      context: ./
      dockerfile: ./apps/urls/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local
